version: '3.7'

services:
  database:
    image: postgres
    container_name: ecommerce
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=database
      - POSTGRES_DB=ecommerce
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  app:
    build: .
    container_name: api-vendas
    restart: always
    ports:
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
